### ISSUE TITLE
"Error in serialize(data, node$con, xdr = FALSE)" when running runPCA

### ISSUE THREAD

**Issue by ycl6** [alanocallaghan/scater#148] opened 2021-05-24 14:08 UTC
After a recent update of R (4.0.5) and some packages, I encounter the follow error message when running `runPCA` with `BPPARAM=MulticoreParam(n)`.

```
Error in serialize(data, node$con, xdr = FALSE) : 
  error writing to connection
```

```
> traceback()
16: serialize(data, node$con, xdr = FALSE)
15: sendData.SOCK0node(backend[[node]], value)
14: parallel:::sendData(backend[[node]], value)
13: .send_to(cluster, i, .DONE())
12: .send_to(cluster, i, .DONE())
11: .bpstop_nodes(x)
10: .bpstop_impl(x)
9: bpstop(BPPARAM)
8: bpstop(BPPARAM)
7: .calculate_pca(mat, transposed = !is.null(dimred), ...)
6: .local(x, ...)
5: calculatePCA(y, ...)
4: calculatePCA(y, ...)
3: .local(x, ...)
2: runPCA(sce.mam, subset_row = top.mam, BPPARAM = MulticoreParam(1))
1: runPCA(sce.mam, subset_row = top.mam, BPPARAM = MulticoreParam(1))
```
I can reporduce the error using public dataset `BachMammaryData` that has 25806 cells. Parallel computing was used when running `modelGeneVarByPoisson()` and `runTSNE()` without error. When running `runPCA()`, I even tried setting `MulticoreParam(workers=1)` but still resulted in error.

```R
library(AnnotationHub)
library(BiocParallel)
library(scater)
library(scran)

sce.mam <- scRNAseq::BachMammaryData()
rownames(sce.mam) <- uniquifyFeatureNames(rowData(sce.mam)$Ensembl, rowData(sce.mam)$Symbol)

ens.mm.v97 <- AnnotationHub()[["AH73905"]]
rowData(sce.mam)$SEQNAME <- mapIds(ens.mm.v97, keys=rowData(sce.mam)$Ensembl, keytype="GENEID", column="SEQNAME")

is.mito <- rowData(sce.mam)$SEQNAME == "MT"
stats <- perCellQCMetrics(sce.mam, subsets=list(Mito=which(is.mito)))
qc <- quickPerCellQC(stats, percent_subsets="subsets_Mito_percent")
sce.mam <- sce.mam[,!qc$discard]

set.seed(12345)
clusters <- quickCluster(sce.mam, min.size=100)
sce.mam <- computeSumFactors(sce.mam, clusters=clusters)
sce.mam <- logNormCounts(sce.mam)

### No error
set.seed(12345)
dec.mam <- modelGeneVarByPoisson(sce.mam, block=sce.mam$Sample, BPPARAM=MulticoreParam(6))
top.mam <- getTopHVGs(dec.mam, prop=0.1)

### Result in "Error in serialize..."
set.seed(12345)
sce.mam <- runPCA(sce.mam, subset_row=top.mam, BPPARAM=MulticoreParam(6))

### Result in "Error in serialize..." even when workers=1
set.seed(12345)
sce.mam <- runPCA(sce.mam, subset_row=top.mam, BPPARAM=MulticoreParam(1))

### No error
set.seed(12345)
sce.mam <- runPCA(sce.mam, subset_row=top.mam, BPPARAM=SerialParam())

### No error
set.seed(12345)
sce.mam <- runTSNE(sce.mam, dimred="PCA", n_threads=6, BPPARAM=MulticoreParam(6))
```

<details>
<summary>sessionInfo</summary>

```R
R version 4.0.5 (2021-03-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS/LAPACK: /home/ihsuan/miniconda3/envs/jupyterlab/lib/libopenblasp-r0.3.15.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8   
 [6] LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ensembldb_2.14.1            AnnotationFilter_1.14.0     GenomicFeatures_1.42.3      AnnotationDbi_1.52.0        scRNAseq_2.4.0             
 [6] scran_1.18.7                scater_1.18.6               ggplot2_3.3.3               SingleCellExperiment_1.12.0 SummarizedExperiment_1.20.0
[11] Biobase_2.50.0              GenomicRanges_1.42.0        GenomeInfoDb_1.26.7         IRanges_2.24.1              S4Vectors_0.28.1           
[16] MatrixGenerics_1.2.1        matrixStats_0.58.0          BiocParallel_1.24.1         AnnotationHub_2.22.1        BiocFileCache_1.14.0       
[21] dbplyr_2.1.1                BiocGenerics_0.36.1        

loaded via a namespace (and not attached):
 [1] Rtsne_0.15                    ggbeeswarm_0.6.0              colorspace_2.0-1              ellipsis_0.3.2               
 [5] scuttle_1.0.4                 bluster_1.0.0                 XVector_0.30.0                BiocNeighbors_1.8.2          
 [9] rstudioapi_0.13               bit64_4.0.5                   interactiveDisplayBase_1.28.0 fansi_0.4.2                  
[13] xml2_1.3.2                    sparseMatrixStats_1.2.1       cachem_1.0.5                  Rsamtools_2.6.0              
[17] shiny_1.6.0                   BiocManager_1.30.15           compiler_4.0.5                httr_1.4.2                   
[21] dqrng_0.3.0                   lazyeval_0.2.2                assertthat_0.2.1              Matrix_1.3-3                 
[25] fastmap_1.1.0                 limma_3.46.0                  later_1.2.0                   BiocSingular_1.6.0           
[29] htmltools_0.5.1.1             prettyunits_1.1.1             tools_4.0.5                   rsvd_1.0.5                   
[33] igraph_1.2.6                  gtable_0.3.0                  glue_1.4.2                    GenomeInfoDbData_1.2.4       
[37] dplyr_1.0.6                   rappdirs_0.3.3                Rcpp_1.0.6                    vctrs_0.3.8                  
[41] Biostrings_2.58.0             ExperimentHub_1.16.1          rtracklayer_1.50.0            DelayedMatrixStats_1.12.3    
[45] stringr_1.4.0                 beachmat_2.6.4                mime_0.10                     lifecycle_1.0.0              
[49] irlba_2.3.3                   statmod_1.4.36                XML_3.99-0.6                  edgeR_3.32.1                 
[53] zlibbioc_1.36.0               scales_1.1.1                  ProtGenerics_1.22.0           hms_1.1.0                    
[57] promises_1.2.0.1              yaml_2.2.1                    curl_4.3.1                    memoise_2.0.0                
[61] gridExtra_2.3                 biomaRt_2.46.3                stringi_1.6.2                 RSQLite_2.2.7                
[65] BiocVersion_3.12.0            rlang_0.4.11                  pkgconfig_2.0.3               bitops_1.0-7                 
[69] lattice_0.20-44               purrr_0.3.4                   GenomicAlignments_1.26.0      bit_4.0.4                    
[73] tidyselect_1.1.1              magrittr_2.0.1                R6_2.5.0                      generics_0.1.0               
[77] DelayedArray_0.16.3           DBI_1.1.1                     pillar_1.6.1                  withr_2.4.2                  
[81] RCurl_1.98-1.3                tibble_3.1.2                  crayon_1.4.1                  utf8_1.2.1                   
[85] viridis_0.6.1                 progress_1.2.2                locfit_1.5-9.4                grid_4.0.5                   
[89] blob_1.2.1                    digest_0.6.27                 xtable_1.8-4                  httpuv_1.6.1                 
[93] openssl_1.4.4                 munsell_0.5.0                 beeswarm_0.3.1                viridisLite_0.4.0            
[97] vipor_0.4.5                   askpass_1.1                  
```
</details>

**Comment by alanocallaghan** [comment] 2021-05-24 15:07
The bpparam in runTSNE isn't doing anything when `external_neighbors=FALSE` (the default)

**Comment by alanocallaghan** [comment] 2021-05-24 15:14
Is `Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal` part of the error message?

**Comment by ycl6** [comment] 2021-05-24 15:32
> The bpparam in runTSNE isn't doing anything when `external_neighbors=FALSE` (the default)

Thanks!

> Is `Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal` part of the error message?

Oh, yes, this message came up sometimes

```R
> set.seed(12345)
sce.mam <- runPCA(sce.mam, subset_row=top.mam, BPPARAM=MulticoreParam(1))
Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal
```

```R
> traceback()
16: serialize(data, node$con, xdr = FALSE)
15: sendData.SOCK0node(backend[[node]], value)
14: parallel:::sendData(backend[[node]], value)
13: .send_to(cluster, i, .DONE())
12: .send_to(cluster, i, .DONE())
11: .bpstop_nodes(x)
10: .bpstop_impl(x)
9: bpstop(BPPARAM)
8: bpstop(BPPARAM)
7: .calculate_pca(mat, transposed = !is.null(dimred), ...)
6: .local(x, ...)
5: calculatePCA(y, ...)
4: calculatePCA(y, ...)
3: .local(x, ...)
2: runPCA(sce.mam, subset_row = top.mam, BPPARAM = MulticoreParam(1))
1: runPCA(sce.mam, subset_row = top.mam, BPPARAM = MulticoreParam(1))
```

**Comment by alanocallaghan** [comment] 2021-05-24 16:03
This seems to happen in BiocSingular, since the following produces much the same error:
```r
sce.mam <- runPCA(t(logcounts(sce.mam)[top.mam, ]), rank = 50, BPPARAM=MulticoreParam(6))
```

traceback is: 
```
10: serialize(data, node$con, xdr = FALSE)
9: sendData.SOCK0node(backend[[node]], value)
8: parallel:::sendData(backend[[node]], value)
7: .send_to(cluster, i, .DONE())
6: .send_to(cluster, i, .DONE())
5: .bpstop_nodes(x)
4: .bpstop_impl(x)
3: bpstop(e[["self"]])
2: bpstop(e[["self"]])
1: (function (e) 
   bpstop(e[["self"]]))(<environment>)
```

**Comment by ycl6** [comment] 2021-05-24 16:30
I also tried parallel computing for `fastMNN()`, both with default `BSPARAM` and `BNPARAM`, as well as using randomized SVD and approximate nearest-neighbor detection, and they ran without error.

```R
> set.seed(12345)
corrected <- batchelor::fastMNN(sce.mam, subset.row=top.mam, batch=sce.mam$Sample, BPPARAM = MulticoreParam(6))

> set.seed(12345)
corrected <- batchelor::fastMNN(sce.mam, subset.row=top.mam, batch=sce.mam$Sample,                  
                                BSPARAM = BiocSingular::RandomParam(deferred = TRUE),
                                BNPARAM = BiocNeighbors::AnnoyParam(), BPPARAM = MulticoreParam(6))
```

**Comment by LTLA** [comment] 2021-05-24 16:43
I suspect that 

https://github.com/Alanocallaghan/scater/blob/207e91e80f42690394a450c2a908d082b4ca74bb/R/runPCA.R#L124

should be 

```r
    if (.bpNotSharedOrUp(BPPARAM)) {
```

Note the omission of the `!`. The idea is to only run `bpstart()` and `bpstop()` for parallel backends that need an explicit start-up (i.e., not forks with shared memory pages) or are not already up. Looks like I made the same mistake in `scran::fixedPCA`, which is not surprising as I just copied it from here.

**Comment by ycl6** [comment] 2021-05-24 16:56
@LTLA Thanks for debugging this.
I'm happy to try this out if the github source is updated.

**Comment by LTLA** [comment] 2021-05-24 17:00
I should also mention I can't reproduce the issue on my machine. The **scater** code is probably wrong regardless, but there is also likely an issue with `bpstart()` and `bpstop()` on MCParam objects. @Alanocallaghan if you can reproduce this and distill it down to a small example, that should be reported to **BiocParallel** repo.

Also, setting `BPPARAM=` to use multiple cores for anything fewer than several hundred thousand cells is usually counterproductive, the overhead of spinning up R-level processes is usually much greater than any speed-up.

**Comment by alanocallaghan** [comment] 2021-06-14 20:44
Should be fixed in release and devel now

**Closed as completed by alanocallaghan** 2021-06-14 20:44 UTC
