### ISSUE TITLE
Matrix 1.6.2 update as_cholmod_sparse issue with runPCA

### ISSUE THREAD

**Issue by Michael-Geuenich** [alanocallaghan/scater#201] opened 2023-11-09 15:53 UTC
Not sure if this is an issue related to scater or Matrix, but it looks like the matrix 1.6.2 update breaks the runPCA function. I get the following error when trying to calculate a PCA embedding 
```sce <- runPCA(sce)
Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  :
  function 'as_cholmod_sparse' not provided by package 'Matrix'
```

This looks potentially related to https://github.com/bwlewis/irlba/issues/70. I am running Matrix 1.6.2

My full sessionInfo()
```R version 4.3.1 (2023-06-16)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Rocky Linux 8.8 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblaso-r0.3.15.so;  LAPACK version 3.9.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C

time zone: America/Toronto
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] scater_1.28.0               ggplot2_3.4.4
 [3] scuttle_1.10.2              SingleCellExperiment_1.22.0
 [5] SummarizedExperiment_1.30.2 Biobase_2.60.0
 [7] GenomicRanges_1.52.1        GenomeInfoDb_1.36.4
 [9] IRanges_2.34.1              S4Vectors_0.38.2
[11] BiocGenerics_0.46.0         MatrixGenerics_1.12.3
[13] matrixStats_1.1.0

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3        jsonlite_1.8.7
  [3] magrittr_2.0.3            ggbeeswarm_0.7.2
  [5] spatstat.utils_3.0-4      zlibbioc_1.46.0
  [7] vctrs_0.6.4               ROCR_1.0-11
  [9] DelayedMatrixStats_1.22.6 spatstat.explore_3.2-5
 [11] RCurl_1.98-1.13           htmltools_0.5.7
 [13] S4Arrays_1.0.5            BiocNeighbors_1.18.0
 [15] sctransform_0.4.1         parallelly_1.36.0
 [17] KernSmooth_2.23-21        htmlwidgets_1.6.2
 [19] ica_1.0-3                 plyr_1.8.9
 [21] plotly_4.10.3             zoo_1.8-12
 [23] igraph_1.5.1              mime_0.12
 [25] lifecycle_1.0.4           pkgconfig_2.0.3
 [27] rsvd_1.0.5                Matrix_1.6-2
 [29] R6_2.5.1                  fastmap_1.1.1
 [31] GenomeInfoDbData_1.2.10   fitdistrplus_1.1-11
 [33] future_1.33.0             shiny_1.7.5.1
 [35] digest_0.6.33             colorspace_2.1-0
 [37] patchwork_1.1.3           Seurat_5.0.0
 [39] tensor_1.5                RSpectra_0.16-1
 [41] irlba_2.3.5.1             beachmat_2.16.0
 [43] progressr_0.14.0          fansi_1.0.5
 [45] spatstat.sparse_3.0-3     httr_1.4.7
 [47] polyclip_1.10-6           abind_1.4-5
 [49] compiler_4.3.1            withr_2.5.2
 [51] BiocParallel_1.34.2       viridis_0.6.4
 [53] fastDummies_1.7.3         MASS_7.3-60
 [55] DelayedArray_0.26.7       tools_4.3.1
 [57] vipor_0.4.5               lmtest_0.9-40
 [59] beeswarm_0.4.0            httpuv_1.6.12
 [61] future.apply_1.11.0       goftest_1.2-3
 [63] glue_1.6.2                nlme_3.1-162
 [65] promises_1.2.1            grid_4.3.1
 [67] Rtsne_0.16                cluster_2.1.4
 [69] reshape2_1.4.4            generics_0.1.3
 [71] gtable_0.3.4              spatstat.data_3.0-3
 [73] tidyr_1.3.0               data.table_1.14.8
 [75] ScaledMatrix_1.8.1        BiocSingular_1.16.0
 [77] sp_2.1-1                  utf8_1.2.4
 [79] XVector_0.40.0            spatstat.geom_3.2-7
 [81] RcppAnnoy_0.0.21          ggrepel_0.9.4
 [83] RANN_2.6.1                pillar_1.9.0
 [85] stringr_1.5.0             spam_2.10-0
 [87] RcppHNSW_0.5.0            later_1.3.1
 [89] splines_4.3.1             dplyr_1.1.3
 [91] lattice_0.21-8            survival_3.5-5
 [93] deldir_1.0-9              tidyselect_1.2.0
 [95] miniUI_0.1.1.1            pbapply_1.7-2
 [97] gridExtra_2.3             scattermore_1.2
 [99] stringi_1.7.12            lazyeval_0.2.2
[101] codetools_0.2-19          tibble_3.2.1
[103] cli_3.6.1                 uwot_0.1.16
[105] xtable_1.8-4              reticulate_1.34.0
[107] munsell_0.5.0             Rcpp_1.0.11
[109] globals_0.16.2            spatstat.random_3.2-1
[111] png_0.1-8                 parallel_4.3.1
[113] ellipsis_0.3.2            dotCall64_1.1-0
[115] sparseMatrixStats_1.12.2  bitops_1.0-7
[117] listenv_0.9.0             viridisLite_0.4.2
[119] scales_1.2.1              ggridges_0.5.4
[121] SeuratObject_5.0.0        leiden_0.4.3
[123] purrr_1.0.2               crayon_1.5.2
[125] rlang_1.1.2               cowplot_1.1.1
```

In fact, when I downgrade to Matrix 1.6.1 it works just fine. My session once downgraded:
```
sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Rocky Linux 8.8 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblaso-r0.3.15.so;  LAPACK version 3.9.0

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_CA.UTF-8
 [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_CA.UTF-8
 [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C

time zone: America/Toronto
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] scater_1.28.0               ggplot2_3.4.4
 [3] scuttle_1.10.2              SingleCellExperiment_1.22.0
 [5] SummarizedExperiment_1.30.2 Biobase_2.60.0
 [7] GenomicRanges_1.52.1        GenomeInfoDb_1.36.4
 [9] IRanges_2.34.1              S4Vectors_0.38.2
[11] BiocGenerics_0.46.0         MatrixGenerics_1.12.3
[13] matrixStats_1.1.0           Matrix_1.6-1.1

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3        jsonlite_1.8.7
  [3] magrittr_2.0.3            spatstat.utils_3.0-4
  [5] ggbeeswarm_0.7.2          zlibbioc_1.46.0
  [7] vctrs_0.6.4               ROCR_1.0-11
  [9] spatstat.explore_3.2-5    DelayedMatrixStats_1.22.6
 [11] RCurl_1.98-1.13           htmltools_0.5.7
 [13] S4Arrays_1.0.5            BiocNeighbors_1.18.0
 [15] sctransform_0.4.1         parallelly_1.36.0
 [17] KernSmooth_2.23-21        htmlwidgets_1.6.2
 [19] ica_1.0-3                 plyr_1.8.9
 [21] plotly_4.10.3             zoo_1.8-12
 [23] igraph_1.5.1              mime_0.12
 [25] lifecycle_1.0.4           pkgconfig_2.0.3
 [27] rsvd_1.0.5                R6_2.5.1
 [29] fastmap_1.1.1             GenomeInfoDbData_1.2.10
 [31] fitdistrplus_1.1-11       future_1.33.0
 [33] shiny_1.7.5.1             digest_0.6.33
 [35] colorspace_2.1-0          patchwork_1.1.3
 [37] tensor_1.5                Seurat_5.0.0
 [39] RSpectra_0.16-1           irlba_2.3.5.1
 [41] beachmat_2.16.0           progressr_0.14.0
 [43] spatstat.sparse_3.0-3     fansi_1.0.5
 [45] polyclip_1.10-6           httr_1.4.7
 [47] abind_1.4-5               compiler_4.3.1
 [49] withr_2.5.2               BiocParallel_1.34.2
 [51] viridis_0.6.4             fastDummies_1.7.3
 [53] MASS_7.3-60               DelayedArray_0.26.7
 [55] tools_4.3.1               vipor_0.4.5
 [57] lmtest_0.9-40             beeswarm_0.4.0
 [59] httpuv_1.6.12             future.apply_1.11.0
 [61] goftest_1.2-3             glue_1.6.2
 [63] nlme_3.1-162              promises_1.2.1
 [65] grid_4.3.1                Rtsne_0.16
 [67] cluster_2.1.4             reshape2_1.4.4
 [69] generics_0.1.3            spatstat.data_3.0-3
 [71] gtable_0.3.4              tidyr_1.3.0
 [73] data.table_1.14.8         BiocSingular_1.16.0
 [75] ScaledMatrix_1.8.1        sp_2.1-1
 [77] utf8_1.2.4                XVector_0.40.0
 [79] spatstat.geom_3.2-7       RcppAnnoy_0.0.21
 [81] stringr_1.5.0             ggrepel_0.9.4
 [83] RANN_2.6.1                pillar_1.9.0
 [85] spam_2.10-0               RcppHNSW_0.5.0
 [87] later_1.3.1               splines_4.3.1
 [89] dplyr_1.1.3               lattice_0.21-8
 [91] deldir_1.0-9              survival_3.5-5
 [93] tidyselect_1.2.0          miniUI_0.1.1.1
 [95] pbapply_1.7-2             gridExtra_2.3
 [97] scattermore_1.2           stringi_1.7.12
 [99] lazyeval_0.2.2            codetools_0.2-19
[101] tibble_3.2.1              cli_3.6.1
[103] uwot_0.1.16               xtable_1.8-4
[105] reticulate_1.34.0         munsell_0.5.0
[107] Rcpp_1.0.11               spatstat.random_3.2-1
[109] globals_0.16.2            png_0.1-8
[111] parallel_4.3.1            ellipsis_0.3.2
[113] dotCall64_1.1-0           sparseMatrixStats_1.12.2
[115] bitops_1.0-7              listenv_0.9.0
[117] viridisLite_0.4.2         scales_1.2.1
[119] ggridges_0.5.4            SeuratObject_5.0.0
[121] leiden_0.4.3              purrr_1.0.2
[123] crayon_1.5.2              rlang_1.1.2
[125] cowplot_1.1.1
```

**Comment by PeteHaitch** [comment] 2023-11-09 20:34
I also first hit it with `scater::runPCA()` and you're right that this is the root cause of this is https://github.com/bwlewis/irlba/issues/70.
If you want to use the latest version of **Matrix**, you might try re-installing **Matrix** and then **irlba**, both from source, which seemed to resolve the issue in my case (https://github.com/bwlewis/irlba/issues/70#issuecomment-1804640397). 
I imagine there will be a a more seamless solution in the coming days.

**Comment by ngamble** [comment] 2023-11-25 02:16
After running around in circles for a while, turns out the key words (for me) were "from source"! Thanks so much @PeteHaitch!

**Comment by alanocallaghan** [comment] 2024-06-21 12:38
Closing as hopefully not popping up any more and nothing I could do regardless

**Closed as completed by alanocallaghan** 2024-06-21 12:38 UTC
