### ISSUE TITLE
How to arrange the "row order" in plotHeatmap() or "gene order" in plotExpression() for scater package?

### ISSUE THREAD

**Issue by crebli** [alanocallaghan/scater#107] opened 2020-04-16 08:05 UTC
For the function plotExpression() in package scater, we are unable to arrange the order of genes. The default order of a list of genes are arranged just in alphabetical order.
It's the same problem for function plotHeatmap() in package scater, that a list of genes are ploted and displayed in alphabetical order if we set argument "cluster_rows = FALSE".
So we recommend to set up arguments to manipulate the gene order in these two functions in package scater: plotExpression() and plotHeatmap().

**Comment by LTLA** [comment] 2020-04-16 08:11
> For the function plotExpression() in package scater, we are unable to arrange the order of genes. The default order of a list of genes are arranged just in alphabetical order.

Fixed in 9c7744ec823fefac1424c5a7edb2627a0698d0c7.

**Comment by crebli** [comment] 2020-04-16 08:19
It is very nice! I appreciate your quick fixation and reply. 
and for function plotHeatmap() , It faces the same problem, could you also fix it at your convenince?

**Comment by LTLA** [comment] 2020-04-17 04:18
Are you sure that `cluster_rows=FALSE` doesn't work? This works fine for me:

```r
library(scater)
example_sce <- mockSCE()
example_sce <- logNormCounts(example_sce)

# Reversed alphabetical order is respected.
plotHeatmap(example_sce, 
    features=rev(rownames(example_sce)[1:10]), cluster_rows=FALSE)
```

<details>
<summary>Session information</summary>

```
R Under development (unstable) (2020-03-23 r78035)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /home/luna/Software/R/trunk/lib/libRblas.so
LAPACK: /home/luna/Software/R/trunk/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] scater_1.15.30              ggplot2_3.3.0              
 [3] SingleCellExperiment_1.9.3  SummarizedExperiment_1.17.5
 [5] DelayedArray_0.13.12        matrixStats_0.56.0         
 [7] Biobase_2.47.3              GenomicRanges_1.39.3       
 [9] GenomeInfoDb_1.23.17        IRanges_2.21.8             
[11] S4Vectors_0.25.15           BiocGenerics_0.33.3        

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6             RColorBrewer_1.1-2       vipor_0.4.5             
 [4] compiler_4.0.0           pillar_1.4.3             XVector_0.27.2          
 [7] viridis_0.5.1            DelayedMatrixStats_1.9.1 BiocNeighbors_1.5.4     
[10] bitops_1.0-6             tools_4.0.0              zlibbioc_1.33.1         
[13] viridisLite_0.3.0        lifecycle_0.2.0          tibble_3.0.0            
[16] gtable_0.3.0             lattice_0.20-41          pkgconfig_2.0.3         
[19] rlang_0.4.5              Matrix_1.2-18            cli_2.0.2               
[22] beeswarm_0.2.3           gridExtra_2.3            GenomeInfoDbData_1.2.3  
[25] withr_2.1.2              dplyr_0.8.5              vctrs_0.2.4             
[28] tidyselect_1.0.0         grid_4.0.0               glue_1.4.0              
[31] R6_2.4.1                 fansi_0.4.1              BiocParallel_1.21.2     
[34] ggbeeswarm_0.6.0         pheatmap_1.0.12          irlba_2.3.3             
[37] BiocSingular_1.3.2       purrr_0.3.3              magrittr_1.5            
[40] scales_1.1.0             ellipsis_0.3.0           rsvd_1.0.3              
[43] assertthat_0.2.1         colorspace_1.4-1         RCurl_1.98-1.1          
[46] munsell_0.5.0            crayon_1.3.4            
```
</details>

**Comment by crebli** [comment] 2020-04-17 05:10
hello，
I have run with rev() function according to your suggestion. Unfortunately, the list of genes are shown in decreasing pattern. The order of the genes is still not as that I input: c("Dmrt1","Ccnd1", "Dmc1", "Rhox13", "Stra8","Tex12","Sycp1", "Hmgb2","Psma8", "Piwil1","Calm2", "Pou5f2","Ddx51","Cdk1","Ccna1", "Tssk5","Tex36","Sun5", "Tex29", "Dcdc2c", "Trim42", "Cdyl","Tnp1", "Tnp2","Prm1","Gapdhs", "Car2"),
   




below are generated by seurat3.1

**Comment by LTLA** [comment] 2020-04-17 05:16
I'm not sure what to say, here. As you can see in this example, I can easily change the order:

```r
library(scater)
example_sce <- mockSCE()
example_sce <- logNormCounts(example_sce)

plotHeatmap(example_sce, 
    features=c("Gene_0010", "Gene_0003", "Gene_0007"), cluster_rows=FALSE)
```

![alpha](https://user-images.githubusercontent.com/8166669/79534532-b2cfc300-802f-11ea-871e-f30e6066d1a6.png)

And again:

```r
plotHeatmap(example_sce, 
    features=c("Gene_0002", "Gene_0010", "Gene_0005"), cluster_rows=FALSE)
```

![bravo](https://user-images.githubusercontent.com/8166669/79534588-d5fa7280-802f-11ea-9691-32d1f2251254.png)

Make sure you're using the latest version of **scater** (1.14.6).

**Comment by crebli** [comment] 2020-04-17 05:32
I have checked my scater verion as for Windows system: 
> package.version("scater")

[1] "1.14.0"

I think it version 1.14.6 is not available for windown system, but it available for Mac system.

**Comment by LTLA** [comment] 2020-04-17 05:40
I cannot reproduce your problem with 1.14.0. I have no issues with controlling the row names:

```r
# Pulling out some example data.
library(scRNAseq)
sce <- ZeiselBrainData()

# Computing log-expression values.
library(scater)
sce <- logNormCounts(sce)

# Creating a heatmap with a predefined gene order.
plotHeatmap(sce, features=c("Snap25", "Gad1", "Malat1", "Actb", "Cd3e"),
    cluster_rows=FALSE)
```

![blah](https://user-images.githubusercontent.com/8166669/79535674-fc6ddd00-8032-11ea-8acd-7cec57961478.png)

If you cannot provide a reproducible example, I will consider this matter closed.

<details>
<summary>Session information</summary>

```
R version 3.6.1 Patched (2019-10-30 r77342)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /home/luna/Software/R/R-3-6-branch/lib/libRblas.so
LAPACK: /home/luna/Software/R/R-3-6-branch/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] scRNAseq_2.0.2              scater_1.14.0              
 [3] ggplot2_3.3.0               SingleCellExperiment_1.8.0 
 [5] SummarizedExperiment_1.16.1 DelayedArray_0.12.2        
 [7] BiocParallel_1.20.1         matrixStats_0.56.0         
 [9] Biobase_2.46.0              GenomicRanges_1.38.0       
[11] GenomeInfoDb_1.22.0         IRanges_2.20.2             
[13] S4Vectors_0.24.3            BiocGenerics_0.32.0        

loaded via a namespace (and not attached):
 [1] viridis_0.5.1                 httr_1.4.1                   
 [3] BiocSingular_1.2.2            bit64_0.9-7                  
 [5] viridisLite_0.3.0             AnnotationHub_2.18.0         
 [7] DelayedMatrixStats_1.8.0      shiny_1.4.0.2                
 [9] assertthat_0.2.1              interactiveDisplayBase_1.24.0
[11] BiocManager_1.30.10           BiocFileCache_1.10.2         
[13] blob_1.2.1                    GenomeInfoDbData_1.2.2       
[15] vipor_0.4.5                   yaml_2.2.1                   
[17] BiocVersion_3.10.1            pillar_1.4.3                 
[19] RSQLite_2.2.0                 lattice_0.20-40              
[21] glue_1.3.2                    digest_0.6.25                
[23] RColorBrewer_1.1-2            promises_1.1.0               
[25] XVector_0.26.0                colorspace_1.4-1             
[27] htmltools_0.4.0               httpuv_1.5.2                 
[29] Matrix_1.2-18                 pkgconfig_2.0.3              
[31] pheatmap_1.0.12               zlibbioc_1.32.0              
[33] xtable_1.8-4                  purrr_0.3.3                  
[35] scales_1.1.0                  later_1.0.0                  
[37] tibble_2.1.3                  withr_2.1.2                  
[39] magrittr_1.5                  crayon_1.3.4                 
[41] mime_0.9                      memoise_1.1.0                
[43] beeswarm_0.2.3                tools_3.6.1                  
[45] lifecycle_0.2.0               munsell_0.5.0                
[47] irlba_2.3.3                   AnnotationDbi_1.48.0         
[49] compiler_3.6.1                rsvd_1.0.3                   
[51] rlang_0.4.5                   grid_3.6.1                   
[53] RCurl_1.98-1.1                BiocNeighbors_1.4.2          
[55] rappdirs_0.3.1                bitops_1.0-6                 
[57] ExperimentHub_1.12.0          gtable_0.3.0                 
[59] DBI_1.1.0                     curl_4.3                     
[61] R6_2.4.1                      gridExtra_2.3                
[63] dplyr_0.8.5                   fastmap_1.0.1                
[65] bit_1.1-15.2                  ggbeeswarm_0.6.0             
[67] Rcpp_1.0.4                    vctrs_0.2.4                  
[69] dbplyr_1.4.2                  tidyselect_1.0.0             
```
</details>

**Comment by crebli** [comment] 2020-04-17 05:46
Yes, it fixed. I have tryied again, it works well now. I don't know what's wrong with my input before. Thank you very much for your patience. 


Best


Yinchuan Li

**Closed as completed** 2020-04-17 05:47 UTC

**Comment by crebli** [comment] 2020-04-27 10:35
hi，Mr. Lun,
As for the newest scater developing version 1.15.32, we are unable to install into R3.6.1 or R4.0.0.  please check it at your convenience.
error information:
object 'make_zero_col_DFrame' is not exported by 'namespace:S4Vectors'
ERROR: lazy loading failed for package 'scater'
* removing 'C:/Program Files/R/R-3.6.1/library/scater'
* restoring previous 'C:/Program Files/R/R-3.6.1/library/scater'
Warning in install.packages :
  installation of package ‘C:/Users/user/Desktop/scater_1.15.32.tar.gz’ had non-zero exit status

**Comment by LTLA** [comment] 2020-04-28 07:10
Run `BiocManager::valid()` and fix all problems.

**Comment by crebli** [comment] 2020-04-29 10:37
hello，
Thanks a lot. But after running BiocManager::valid() with R3.6.1, it is still unable to launch scater_1.15.32. I think my R environment doesn't work well. 




the information are as follows: 
> install.packages("C:/Users/user/Desktop/scater_1.15.32.tar.gz", repos = NULL, type = "source")
* installing *source* package 'scater' ...
** using staged installation
** libs


*** arch - i386
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.1/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.1/library/beachmat/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.1/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.1/library/beachmat/include"        -O2 -Wall  -mtune=generic -c combined_qc.cpp -o combined_qc.o
combined_qc.cpp: In function 'void check_topset(const IntegerVector&)':
combined_qc.cpp:14:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t t=1; t<top.size(); ++t) {
                       ^
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.1/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.1/library/beachmat/include"        -O2 -Wall  -mtune=generic -c sum_counts.cpp -o sum_counts.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.1/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.1/library/beachmat/include"        -O2 -Wall  -mtune=generic -c utils.cpp -o utils.o
C:/RBuildTools/3.5/mingw_32/bin/g++ -shared -s -static-libgcc -o scater.dll tmp.def RcppExports.o combined_qc.o sum_counts.o utils.o -LC:/PROGRA~1/R/R-36~1.1/bin/i386 -lR
installing to C:/Program Files/R/R-3.6.1/library/00LOCK-scater/00new/scater/libs/i386


*** arch - x64
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.1/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.1/library/beachmat/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.1/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.1/library/beachmat/include"        -O2 -Wall  -mtune=generic -c combined_qc.cpp -o combined_qc.o
combined_qc.cpp: In function 'void check_topset(const IntegerVector&)':
combined_qc.cpp:14:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t t=1; t<top.size(); ++t) {
                       ^
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.1/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.1/library/beachmat/include"        -O2 -Wall  -mtune=generic -c sum_counts.cpp -o sum_counts.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.6.1/library/Rcpp/include" -I"C:/Program Files/R/R-3.6.1/library/beachmat/include"        -O2 -Wall  -mtune=generic -c utils.cpp -o utils.o
C:/RBuildTools/3.5/mingw_64/bin/g++ -shared -s -static-libgcc -o scater.dll tmp.def RcppExports.o combined_qc.o sum_counts.o utils.o -LC:/PROGRA~1/R/R-36~1.1/bin/x64 -lR
installing to C:/Program Files/R/R-3.6.1/library/00LOCK-scater/00new/scater/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
Warning messages:
1: 程辑包'SummarizedExperiment'是用R版本3.6.2 来建造的 
2: 程辑包'S4Vectors'是用R版本3.6.3 来建造的 
3: 程辑包'IRanges'是用R版本3.6.2 来建造的 
4: 程辑包'GenomeInfoDb'是用R版本3.6.3 来建造的 
5: 程辑包'DelayedArray'是用R版本3.6.3 来建造的 
6: 程辑包'matrixStats'是用R版本3.6.3 来建造的 
7: 程辑包'BiocParallel'是用R版本3.6.2 来建造的 
错误: object 'make_zero_col_DFrame' is not exported by 'namespace:S4Vectors'
停止执行
ERROR: lazy loading failed for package 'scater'
* removing 'C:/Program Files/R/R-3.6.1/library/scater'
* restoring previous 'C:/Program Files/R/R-3.6.1/library/scater'
Warning in install.packages :
  installation of package ‘C:/Users/user/Desktop/scater_1.15.32.tar.gz’ had non-zero exit status
> 
















At 2020-04-28 15:10:36, "Aaron Lun" <notifications@github.com> wrote:

Run BiocManager::valid() and fix all problems.

**Comment by LTLA** [comment] 2020-04-30 07:38
You're trying to install a BioC-devel version of **scater** (odd middle number) inside a BioC-release environment (R 3.6.1). If you didn't understand what that meant, you shouldn't be doing it.

Follow the [instructions](https://bioconductor.org/packages/release/bioc/html/scater.html) for installing Bioconductor packages. The use of R 4.0.0 is not optional.

**Comment by crebli** [comment] 2020-05-02 03:55
Thanks!发自我的华为手机-------- 原始邮件 --------发件人： Aaron Lun <notifications@github.com>日期： 2020年4月30日周四 下午3:39收件人： davismcc/scater <scater@noreply.github.com>抄送： crebli <18622397604@163.com>, Author <author@noreply.github.com>主    题： Re: [davismcc/scater] How to arrange the "row order" in plotHeatmap() or "gene order" in plotExpression() for scater package? (#107)
You're trying to install a BioC-devel version of scater (odd middle number) inside a BioC-release environment (R 3.6.1). If you didn't understand what that meant, you shouldn't be doing it.
Follow the instructions for installing Bioconductor packages. The use of R 4.0.0 is not optional.
